### ISSUE TITLE
The package build it failed 

### ISSUE THREAD

**Issue by pursue942** [matrix-org/matrix-wysiwyg-composer-swift#68]
to much error, can't build it. 
such as:
builder.willFlushCallback = { element in
            guard let element else { return }
Variable binding in a condition requires an initializer   guard let element = element else { return } is good.
how to fix other error?  I can't do it.

**Comment by aringenbach** [comment]
Hello @pursue942, the library takes advantage of some of the new allowed syntaxes from Swift 5.7 (see https://developer.apple.com/videos/play/wwdc2022/110354/)

Given your error, I assume you are trying to build with an older version of Swift/Xcode.

**Comment by aringenbach** [comment]
For the record, this is generated from our main repository, I updated the Package.swift [there](https://github.com/matrix-org/matrix-rich-text-editor/pull/626) to reflect that minimal required version properly. It should show up here as well in an upcoming release.
